export const data = [
    {
        "id": 1,
        "tenPhong": "NewApt D1 - Cozy studio - NU apt - 500m Bui Vien!",
        "khach": 3,
        "phongNgu": 1,
        "giuong": 1,
        "phongTam": 1,
        "moTa": "Tự nhận phòng\r\nTự nhận phòng bằng khóa thông minh.\r\nDinh Long là Chủ nhà siêu cấp\r\nChủ nhà siêu cấp là những chủ nhà có kinh nghiệm, được đánh giá cao và là những người cam kết mang lại quãng thời gian ở tuyệt vời cho khách.",
        "giaTien": 28,
        "mayGiat": true,
        "banLa": true,
        "tivi": true,
        "dieuHoa": false,
        "wifi": true,
        "bep": false,
        "doXe": true,
        "hoBoi": true,
        "banUi": true,
        "maViTri": 1,
        "hinhAnh": "https://airbnbnew.cybersoft.edu.vn/images/phong1.jpg"
    },
    {
        "id": 2,
        "tenPhong": "STUDIO MỚI NETFLIX MIỄN PHÍ/ĐỖ XE MIỄN PHÍ",
        "khach": 2,
        "phongNgu": 1,
        "giuong": 1,
        "phongTam": 1,
        "moTa": "Không gian riêng để làm việc\r\nMột khu vực chung có Wi-fi, phù hợp để làm việc.\r\nTự nhận phòng\r\nTự nhận phòng bằng khóa thông minh.\r\nKim Nam là Chủ nhà siêu cấp\r\nChủ nhà siêu cấp là những chủ nhà có kinh nghiệm, được đánh giá cao và là những người cam kết mang lại quãng thời gian ở tuyệt vời cho khách.",
        "giaTien": 21,
        "mayGiat": true,
        "banLa": true,
        "tivi": true,
        "dieuHoa": true,
        "wifi": true,
        "bep": true,
        "doXe": false,
        "hoBoi": false,
        "banUi": false,
        "maViTri": 1,
        "hinhAnh": "https://airbnbnew.cybersoft.edu.vn/images/phong2.png"
    },
    {
        "id": 3,
        "tenPhong": "Phòng sang trọng với ban công tại D.1 - 200m đến Bitexco",
        "khach": 2,
        "phongNgu": 1,
        "giuong": 1,
        "phongTam": 1,
        "moTa": "Emmy là Chủ nhà siêu cấp\r\nChủ nhà siêu cấp là những chủ nhà có kinh nghiệm, được đánh giá cao và là những người cam kết mang lại quãng thời gian ở tuyệt vời cho khách.\r\nTrải nghiệm nhận phòng tuyệt vời\r\n100% khách gần đây đã xếp hạng 5 sao cho quy trình nhận phòng.\r\nHủy miễn phí trước 28 thg 9.",
        "giaTien": 17,
        "mayGiat": true,
        "banLa": true,
        "tivi": true,
        "dieuHoa": false,
        "wifi": false,
        "bep": false,
        "doXe": true,
        "hoBoi": true,
        "banUi": true,
        "maViTri": 1,
        "hinhAnh": "https://airbnbnew.cybersoft.edu.vn/images/phong3.png"
    },
    {
        "id": 232926,
        "tenPhong": "Phong",
        "khach": 5,
        "phongNgu": 5,
        "giuong": 5,
        "phongTam": 5,
        "moTa": "5",
        "giaTien": 5,
        "mayGiat": true,
        "banLa": true,
        "tivi": true,
        "dieuHoa": true,
        "wifi": true,
        "bep": true,
        "doXe": true,
        "hoBoi": true,
        "banUi": true,
        "maViTri": 1,
        "hinhAnh": "https://phunugioi.com/wp-content/uploads/2021/11/hinh-nen-obito-dep-ngau-nhat.jpg"
    }
]